version: "3"
services:
  database:
    container_name: mysql-notification
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: table

  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database