version: "3"
services:
  database:
    container_name: mysql-notification
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_HOST: mysql

  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database

  
  script:
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - mysql --version
    - sleep 20
    - echo "SHOW databases;" | mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h "${MYSQL_HOST}"
    - echo "Database host is '${MYSQL_HOST}'"
